/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Entity2WhereUniqueInput } from "./Entity2WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class DeleteEntity2Args {
  @ApiProperty({
    required: true,
    type: () => Entity2WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Entity2WhereUniqueInput)
  @Field(() => Entity2WhereUniqueInput, { nullable: false })
  where!: Entity2WhereUniqueInput;
}

export { DeleteEntity2Args as DeleteEntity2Args };
