/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Entity2WhereInput } from "./Entity2WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Entity2ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Entity2WhereInput,
  })
  @ValidateNested()
  @Type(() => Entity2WhereInput)
  @IsOptional()
  @Field(() => Entity2WhereInput, {
    nullable: true,
  })
  every?: Entity2WhereInput;

  @ApiProperty({
    required: false,
    type: () => Entity2WhereInput,
  })
  @ValidateNested()
  @Type(() => Entity2WhereInput)
  @IsOptional()
  @Field(() => Entity2WhereInput, {
    nullable: true,
  })
  some?: Entity2WhereInput;

  @ApiProperty({
    required: false,
    type: () => Entity2WhereInput,
  })
  @ValidateNested()
  @Type(() => Entity2WhereInput)
  @IsOptional()
  @Field(() => Entity2WhereInput, {
    nullable: true,
  })
  none?: Entity2WhereInput;
}
export { Entity2ListRelationFilter as Entity2ListRelationFilter };
